# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: sparkgeo/base:circleci
  working_directory: ~/project

jobs:
  build:
    <<: *defaults

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - run:
          name: Lint
          command: npm run lint

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build
          command: npm run build

  deploy-staging:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: deploy to aws
          command: aws s3 sync dist/ s3://staclint.com/staging --delete

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/
      # - deploy-prod:
      #     requires:
      #       - build
      #     context: org-global
      #     filters:
      #       branches:
      #         only: master
      - deploy-staging:
          requires:
            - build
          context: org-global
          filters:
            branches:
              only: /rc[0-9]+(\.[0-9]+)+/
